services:
  ml:
      image: containerized-training:latest
      container_name: containerized-training
      command:
        - python3 
        - test.py
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]